### PR TITLE
Add unofficial installer

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Xenophilicy** [comment]
Nice work, looks really simple and clean 👍

**Comment by nathfreder** [comment]
> Nice work, looks really simple and clean 👍

I'm open to _any_ suggestions though! 😜

**Comment by jasonw4331** [comment]
If it is put on the official pmmp rtfd, doesn't the `unofficial` become `official` because pmmp is supporting it's development? Or maybe it should just be known as a `third-party installer`

**Comment by ghost** [comment]
I’m not sure, it’s up to @dktapps though.

**Comment by nathfreder** [comment]
Since this isn't going anywhere, I'll close.

**Pull request closed without merging**
