### PR TITLE
Update instructions for fixing opcache

### PR DESCRIPTION
**Pull request by unickorn**

### CODE REVIEW

**Comment by dktapps** [comment]
Why is this necessary?

**Comment by unickorn** [comment]
Not sure, I added quotes on mac (zsh) and it worked, otherwise it wouldn't handle regex properly
image

**Comment by dktapps** [comment]
You should check that php.ini actually contains the expected path.

**Comment by unickorn** [comment]
php.ini before running the command without quotes:
```
memory_limit=1024M
date.timezone=UTC
short_open_tag=0
asp_tags=0
phar.require_hash=1
igbinary.compact_strings=0
zend.assertions=-1
error_reporting=-1
display_errors=1
display_startup_errors=1
recursionguard.enabled=0 ;disabled due to minor performance impact, only enable this if you need it for debugging
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=1
opcache.save_comments=1
opcache.validate_timestamps=1
opcache.revalidate_freq=0
opcache.file_update_protection=0
opcache.optimization_level=0x7FFEBFFF ;https://github.com/php/php-src/blob/53c1b485741f31a17b24f4db2b39afeb9f4c8aba/ext/opcache/Optimizer/zend_optimizer.h

; ---- ! WARNING ! ----
; JIT can provide big performance improvements, but as of PHP 8.0.8 it is still unstable. For this reason, it is disabled by default.
; Enable it at your own risk. See https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.jit for possible options.
opcache.jit=off
opcache.jit_buffer_size=128M
```

php.ini after running without quotes
```
<same file with this line following below>
extension_dir=""
```

php.ini after running with quotes
```
<same file, only changes the last line>
extension_dir="/Users/ilhanates/work/php/PocketMine-MP/bin/php7/lib/php/extensions/no-debug-zts-20200930"
```

Pretty sure that is the fix, at least on zsh, I didn't have the chance to test on any other platform.

**Pull request closed without merging**
